name: Update iOS Provisioning Profile

on:
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Setup Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Sync iOS credentials with EAS
        run: eas credentials:sync --platform ios
        env:
          EXPO_APPLE_API_KEY_ID: ${{ secrets.EXPO_APPLE_API_KEY_ID }}
          EXPO_APPLE_API_ISSUER_ID: ${{ secrets.EXPO_APPLE_API_ISSUER_ID }}
          EXPO_APPLE_API_KEY: ${{ secrets.EXPO_APPLE_API_KEY }}
